### PR TITLE
feat: add api v4 support 

### PR DESCRIPTION
**Pull request by KaterinaWire**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Add api v4 support.

The change log:
https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/761266263/API+changes+v3+v4

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by johnxnguyen — COMMENTED** [review]
Without seeing the change log from v3 to v4 I can't tell if this adds support for v4.

**Comment by KaterinaWire** [comment]
> Without seeing the change log from v3 to v4 I can't tell if this adds support for v4.

Done

**Review by David-Henner — APPROVED** [review]

**Review by johnxnguyen — COMMENTED** [review]
I see in the change log some more removed endpoints related to teams, but I don't see those changes here. Did we already move away from these deprecated endpoints?

**Comment by KaterinaWire** [comment]
> I see in the change log some more removed endpoints related to teams, but I don't see those changes here. Did we already move away from these deprecated endpoints?

I left comments in Jira tickets about remote endpoints that we don't use. The only remote endpoint we use is `GET /teams` and we handle it in:
`TeamDownloadRequestStrategy.swift`

**Review by johnxnguyen — APPROVED** [review]

**Pull request merged**
