### PR TITLE
feat: Integration of Hot Reloading with Inject Library - WPB-11098

### PR DESCRIPTION
**Pull request by agisilaos**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-11098" title="WPB-11098" target="_blank">TaskWPB-11098</a>  [iOS] Introduce Hot Reloading on Wire-iOS
  </td></table>
  <br />
 

**Summary:**

This PR introduces **hot reloading** into our project by integrating the **Inject** library via Swift Package Manager (SPM). The first two SwiftUI views that support hot reloading are **AccentColorPicker** and **DeveloperToolsView**. This integration aims to accelerate the development process by allowing real-time UI updates without recompiling the entire app.

More on the library can be found [here](https://github.com/krzysztofzablocki/Inject)

---

**Details:**

1. **Inject Library Integration:**
   - We added the **Inject** library through **SPM** to enable live UI updates while the app is running.
   - This feature is particularly beneficial for **SwiftUI** and **UIKit** views, as it allows changes to be instantly reflected.

2. **Views with Hot Reloading:**
   - **AccentColorPicker** and **DeveloperToolsView** are the first SwiftUI views where hot reloading has been implemented.
   - Hot reloading enables faster iterations and feedback during development by eliminating the need to fully rebuild the app for small UI changes.

3. **Build Configuration Adjustments:**
   - We switched the **compilation mode to Incremental** for **Debug builds** to support hot reloading.
   - This allows quicker compilation by recompiling only the files affected by changes, improving development speed.
   - We needed to add two new flags to `Wire-iOS`

4. **Additional Setup Required:**
   - Developers will need to **download the InjectionIII app** on their machines to enable live code injection.
   - InjectionIII is necessary to monitor file changes and inject them into the running app for immediate updates.

5. **Upcoming Documentation:**
   - A detailed **Confluence page** with step-by-step instructions for setting up and using hot reloading with Inject will be published soon. This will include guidance on how to properly configure InjectionIII and integrate it into your workflow.

---

### Checklist

- [x] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [x] Description is filled and free of optional paragraphs.
- [x] Adds/updates automated tests.

---

### CODE REVIEW

**Review by samwyndham — APPROVED** [review]
It's interesting that you added it to `SwiftUI` views as personally I'm quite happy with `SwiftUI` previews - I can see it being very useful in UIKit though.

**Comment by samwyndham** [comment]
> A detailed Confluence page with step-by-step instructions for setting up and using hot reloading with Inject will be published soon. This will include guidance on how to properly configure InjectionIII and integrate it into your workflow.

I'm wondering if the documentation would be better placed in our project documentation rather than on Confluence 🤔

**Comment by caldrian** [comment]
> I can see it being very useful in UIKit though.

I actually use `#Preview` for UIKit views as well. Works pretty well.
This PR is still useful for all the legacy code in the Wire-iOS project, where the build time is really bad.

**Review by jullianm — APPROVED** [review]

**Comment by agisilaos** [comment]
> > A detailed Confluence page with step-by-step instructions for setting up and using hot reloading with Inject will be published soon. This will include guidance on how to properly configure InjectionIII and integrate it into your workflow.
> 
> I'm wondering if the documentation would be better placed in our project documentation rather than on Confluence 🤔

How to set it up would be in Confluence. How to use it would be inside the project.

**Pull request merged**
