### PR TITLE
fix: optional zmsdispatchgroup

### PR DESCRIPTION
**Pull request by markusfassbender**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Fixes force unwraps on non-optional `ZMSDispatchGroup`.

### Causes (Optional)

- Introduced by #954 although the tests were green.

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

- Run automated test suites

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by caldrian — APPROVED** [review]
One more try:
https://github.com/wireapp/wire-ios/pull/954#discussion_r1483999405

**Review by netbe — APPROVED** [review]

**Review by typfel — COMMENTED** [review]
I don't understand why it was crashing, was any of the `ZMSDispatchGroup()` nil?

**Comment by markusfassbender** [comment]
@typfel no it just could not build:
Screenshot 2024-02-09 at 11 03 11

**Comment by markusfassbender** [comment]
Let's wait for the result of all tests this time:
https://github.com/wireapp/wire-ios/actions/runs/7842255097

**Review by typfel — APPROVED** [review]

**Pull request merged**
