### PR TITLE
fix: protocol update message inserted twice - WPB-6130

### PR DESCRIPTION
**Pull request by markusfassbender**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-6130" title="WPB-6130" target="_blank">BugWPB-6130</a>  [iOS] Protocol update message inserted twice
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

See ticket.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

See ticket.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by typfel** [comment]
So you decided to not go with the solution we discussed in the iOS lounge, how come?

**Comment by markusfassbender** [comment]
@typfel I've tested the change from iOS lounge to use `var created`, but there were multiple events calling this `ConversationEventPayloadProcessor.updateOrCreateGroupConversation`. The change stopped updating group conversations in all cases, not only for `conversation.create` events.
Therefore `updateMessageProtocol(...)` and other functions were not called at anymore and broke existing behaviour e.g. calling `conversation.appendMLSMigrationPotentialGapSystemMessage(…)`, that was implemented recently with [[WPB-535]](https://wearezeta.atlassian.net/browse/WPB-535).
Also I did not really like my own implementation of `ConversationPostProtocolChangeUpdater` in the last PR, we just needed to merge to avoid the long running branch.

[WPB-535]: https://wearezeta.atlassian.net/browse/WPB-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by typfel** [comment]
> @typfel I've tested the change from iOS lounge to use `var created`, but there were multiple events calling this `ConversationEventPayloadProcessor.updateOrCreateGroupConversation`. The change stopped updating group conversations in all cases, not only for `conversation.create` events. Therefore `updateMessageProtocol(...)` and other functions were not called at anymore and broke existing behaviour e.g. calling `conversation.appendMLSMigrationPotentialGapSystemMessage(…)`, that was implemented recently with [[WPB-535](https://wearezeta.atlassian.net/browse/WPB-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)](https://wearezeta.atlassian.net/browse/WPB-535). Also I did not really like my own implementation of `ConversationPostProtocolChangeUpdater` in the last PR, we just needed to merge to avoid the long running branch.

Ok  I see, but couldn't we do guard in 
 
 ```
 func processPayload(
        _ payload: Payload.ConversationEvent<Payload.Conversation>,
        in context: NSManagedObjectContext
    )
   ```

which returns if the conversation already exists. 

--- 

Hmm but I guess that method is also called in other cases.

[WPB-535]: https://wearezeta.atlassian.net/browse/WPB-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by typfel — APPROVED** [review]

**Review by netbe — APPROVED** [review]
LGTM;)

**Pull request merged**
