### PR TITLE
chore: merge develop in feat/mls

### PR DESCRIPTION
**Pull request by David-Henner**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

This PR merges `develop` in `feat/mls`

### CODE REVIEW

**Review by netbe — APPROVED** [review]

**Comment by netbe** [comment]
@David-Henner ok for me once the tests passed, merge the PR. DON'T SQUASH

**Comment by David-Henner** [comment]
> @David-Henner ok for me once the tests passed, merge the PR. DON'T SQUASH

Ok 👍 May I ask the reason?

**Comment by netbe** [comment]
to keep the history

**Comment by netbe** [comment]
closing

**Pull request closed without merging**
