### PR TITLE
chore: Remove wr_randomProfilePictureSource - WPB-9817

### PR DESCRIPTION
**Pull request by samwyndham**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-9817" title="WPB-9817" target="_blank">TaskWPB-9817</a>  remove wr_randomProfilePictureSource
  </td></table>
  <br />
 

### Issue

This PR deletes an uncalled static variable, `WireURL.wr_randomProfilePictureSource` and the underlying data that it depends on. There will be a follow up PR that removes the underlying data from [wire-ios-build-assets](https://github.com/wireapp/wire-ios-build-assets)

### Testing

No testing is necessary as this is unused code. Please confirm @netbe.

---

### Checklist

- [X] Title contains a reference JIRA issue number like `[WPB-XXX]`.
- [X] Description is filled and free of optional paragraphs.
- [ ] Adds/updates automated tests.

### CODE REVIEW

**Review by caldrian — DISMISSED** [review]
👏

**Review by markusfassbender — DISMISSED** [review]
Thanks!

**Review by johnxnguyen — DISMISSED** [review]
🏆 Achievement unlocked: first pull request 🥳

**Comment by samwyndham** [comment]
Requested re-review for minimal changes... The main one being pointing to the latest [wire-ios-build-assets](https://github.com/wireapp/wire-ios-build-assets)

**Review by johnxnguyen — APPROVED** [review]

**Review by markusfassbender — APPROVED** [review]

**Pull request merged**
