### PR TITLE
chore: remove core data models until 2.80 [WPB-5683]

### PR DESCRIPTION
**Pull request by markusfassbender**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5683" title="WPB-5683" target="_blank">TaskWPB-5683</a>  [iOS] drop core data models before 2.80
  </td></table>
  <br />
 

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5683" title="WPB-5683" target="_blank">TaskWPB-5683</a>  [iOS] drop core data models before 2.80
  </td></table>
  <br />
 
---

# What's new in this PR?

### Issues

See ticket.

### Solutions

- Remove all model versions before 2.80
- Remove not needed tests
- Add test to ensure migration step exists

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

- Run unit tests
- Enforce migration by using an old app version and install the new one

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by johnxnguyen — COMMENTED** [review]
Model version 2-80-0 was added on 2020-03-26 in https://github.com/wireapp/wire-ios-data-model/pull/916, which was more than 3 and a half years ago. These changes would mean that anyone still using a build of at least that age would not be able to upgrade to the next version, right?

It may be possible that someone is running such an old build, but if there is I guess it's a very small number of users.

**Comment by lennart-mumm** [comment]
> Model version 2-80-0 was added on 2020-03-26 in [wireapp/wire-ios-data-model#916](https://github.com/wireapp/wire-ios-data-model/pull/916), which was more than 3 and a half years ago. These changes would mean that anyone still using a build of at least that age would not be able to upgrade to the next version, right?
> 
> It may be possible that someone is running such an old build, but if there is I guess it's a very small number of users.

Is there a similar warning in the App Store as there is in the Playstore? In the Playstore it says “If you don’t install updates, the app or key features can stop working entirely, and you will lose your right to make legal claims.” 

From the user app version statistics in Countly, the oldest version I can see right now that is in use is 3.57.944. When was that version released? Apart from this version, I also see a version called 1.07.00000. I am not familiar with this version syntax; from what time is this one?

**Comment by lennart-mumm** [comment]
To add to my previous comment, I think that it is likely correct to go ahead with this, but it would be good to be aware what it would mean to be able to, somewhat, gauge potential ramifications. Also @tmspzz, FYI.

**Comment by markusfassbender** [comment]
1. I've never seen such a warning in the App Store, but use auto updates and don't really visit the release notes nor update pages
2. Version 3.57 was published on 2020-04-29
3. Version 1.7 (the only one I could find) was published on 2015-03-26

About the old versions the user might don't have a device that support iOS 15 and can not download new versions anyway.

**Review by netbe — APPROVED** [review]

**Review by johnxnguyen — APPROVED** [review]

**Pull request merged**
