### PR TITLE
fix: deadlock on launch when checking if we need to migrate to CC WPB-5540 (cherry-pick)

### PR DESCRIPTION
**Pull request by typfel**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5540" title="WPB-5540" target="_blank">BugWPB-5540</a>  [iOS] App gets stuck on splash screen after launching
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Cherry-pick of https://github.com/wireapp/wire-ios/pull/690

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by caldrian — APPROVED** [review]
Could you please try to fix the SwiftLint warnings?

**Comment by typfel** [comment]
> Could you please try to fix the SwiftLint warnings?

I don't know It's failing on files I didn't touch. @agisilaos any idea why SwiftLint behaves like this?

**Comment by agisilaos** [comment]
> > Could you please try to fix the SwiftLint warnings?
> 
> I don't know It's failing on files I didn't touch. @agisilaos any idea why SwiftLint behaves like this?

It runs on all files. Ignore for now.

**Review by agisilaos — APPROVED** [review]

**Comment by markusfassbender** [comment]
@caldrian the SwiftLint check is only red on the release branch, `develop` is green

**Pull request merged**
