### PR TITLE
feat: introduce a default system logger for WireLogger

### PR DESCRIPTION
**Pull request by typfel**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When I run the integration tests I don't get any logs which makes it very hard to debug when a test is failing.

### Causes

WireLogger doesn't have any default provider and the only implementation is the data dog logger which lives in the UI project.

### Solutions

Introduce a default system logger which delegates to `os_log`

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by johnxnguyen — APPROVED** [review]

**Review by netbe — COMMENTED** [review]
@typfel don't you get the print statement in debug though?

**Comment by typfel** [comment]
Which print statement are you referring to?

**Comment by netbe** [comment]
@typfel https://github.com/wireapp/wire-ios/blob/1060a2ffe2c476d08cd681a8e6f79fb4501aefef/wire-ios/Wire-iOS/Sources/Managers/DatadogWrapper.swift#L185-L203

**Comment by typfel** [comment]
> @typfel
> 
> https://github.com/wireapp/wire-ios/blob/1060a2ffe2c476d08cd681a8e6f79fb4501aefef/wire-ios/Wire-iOS/Sources/Managers/DatadogWrapper.swift#L185-L203

The DataDogWrapper lives in the UI project it is not created when running the sync engine integration tests.

**Review by agisilaos — APPROVED** [review]

**Pull request merged**
